# Site
name: 'Junpapa'
description: 'Snow Lover'
logo: 'assets/images/logo.png'
#favicon: 'assets/images/favicon.ico'
#baseurl: '/mundana-theme-jekyll'
baseurl: ''
disqus: 'junpapa'
email: 'junpapa@gmail.com'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-target-blank
  
authors:
    Junpapa:
      name:           Junpapa
      site:           https://run262.github.io
      avatar:         /assets/images/junpapa.jpg
#      bio:            
      email:          junpapa@gmail.com
#      twitter:        https://twitter.com/wowthemesnet

 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Junpapa
      avatar: /assets/images/junpapa.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]